### PR TITLE
[Put in separate branch] Changes for Anaconda integration

### PR DESCRIPTION
**Pull request by Xaenalt**
Force jupyterlab

Add .condarc to limit user from using free packages

Ensure notebook uses /opt/app-root env

## This introduces a breaking change

- [X] Yes
- [ ] No

This work should go into a separate branch, not master

### CODE REVIEW

**Comment by harshad16** [comment]
I will move this to a separate branch then we can work from there.
I thought Github allowed users to push to a different branch.(maybe as there isn't a pre-existing branch, maybe that's the reason).

**Comment by harshad16** [comment]
These changes are moved to the different `anaconda` 
branch https://github.com/thoth-station/s2i-minimal-notebook/tree/anaconda
We are happy to work together on this.
Project Thoth currently doesnt have the support for conda , so our base image maybe not that useful.

**Comment by Xaenalt** [comment]
Right, I had to make a separate image to swap pip for conda

It's likely incompatible with the existing stuff, but there might be some refactoring that could occur

**Comment by goern** [comment]
Is this still something we want?

**Comment by Xaenalt** [comment]
In general I'd like to get the Anaconda notebook into regular cadence with the rest of our stuff so it's not just some image in my quay repo with no real checks on it. Not sure if we want that here or not

**Comment by goern** [comment]
@Xaenalt could you please have a look at the merge conflict?

**Comment by Xaenalt** [comment]
Oh, forgot these were still here, I think it'd probably be best to roll this effort into a more generalized method

**Pull request closed without merging**
