### PR TITLE
Introduce Jupyterlab extension for dependency management

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Related-To: https://github.com/thoth-station/jupyterlab-requirements/issues/53

Related-To: https://github.com/operate-first/support/issues/77

## This introduces a breaking change

- [x] Yes
- [ ] No

## This Pull Request implements

Introduce new extension for jupyterlab for dependency management. (similar to jupyter-nbrequirements for classical jupyter notebook)

Reference: https://github.com/thoth-station/jupyterlab-requirements

Requirements: 

```
Juyterlab >= 3.0.0
python >= 3.8
```

### CODE REVIEW

**Comment by harshad16** [comment]
This is available in the branch https://github.com/thoth-station/s2i-minimal-notebook/tree/jupyterlab3
/hold

**Comment by pacospace** [comment]
> This is available in the branch https://github.com/thoth-station/s2i-minimal-notebook/tree/jupyterlab3
> /hold

I miss `jupyter lab build` command in that image as it is not run in the minimal one, correct @harshad16 ?  the backend part of the extension is not working currently :) 

can we get an image on top of that branch which does `jupyter lab build` and test it in JH on Operate First? If the image on top has Elyra would be a + + + + + :) Thanks!!

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/jupyterlab-requirements/issues/53

**Comment by pacospace** [comment]
> > This is available in the branch https://github.com/thoth-station/s2i-minimal-notebook/tree/jupyterlab3
> > /hold
> 
> I miss `jupyter lab build` command in that image as it is not run in the minimal one, correct @harshad16 ? the backend part of the extension is not working currently :)
> 
> can we get an image on top of that branch which does `jupyter lab build` and test it in JH on Operate First? If the image on top has Elyra would be a + + + + + :) Thanks!!

It is not required actually if setup.py is set correctly: https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb

**Comment by goern** [comment]
what is missing to move this forward?

**Comment by pacospace** [comment]
> what is missing to move this forward?

I think we can close this, as @harshad16 introduced overlays builds: https://github.com/thoth-station/s2i-minimal-notebook/pull/37

I think we can close this right @harshad16 ?

**Comment by harshad16** [comment]
> I think we can close this, as introduced overlays builds: #37 and we include jupyterlab-requirements in the python3.8 version.

The PR image is converted to the PR: #37, it is being refined , so that contributors can understand better.
we can close this PR, if that PR: #37  get merged.
For now there is an available image in `quay.io/thoth-station/s2i-minimal-py38-notebook:jupyterlab-thoth` corresponding to this PR.

**Comment by pacospace** [comment]
Related-To: https://github.com/opendatahub-io/odh-manifests/issues/327

**Pull request merged**
