### PR TITLE
update base image to v0.15.0 and add version file

### PR DESCRIPTION
**Pull request by harshad16**
update base image to v0.15.0 and add version file
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

## Related Issues and Dependencies

Related to release of update base image s2i-thoth-ubi8-py36.

## This introduces a breaking change

- [x] No

## This Pull Request implements
- updated aicoe-ci config file to use  updated s2i-thoth-ubi8-py36 
- introduce a thoth/s2i-minimal-notebook/__init__.py  to allow kebechet to maintain release updates and changelogs.

## Description

kebechet updates semver version change to app.py,wsgi.py,__init__.py to reduce confusion , kept the __init__.py in thoth/s2i-minimal-notebook. Maintainer of s2i-minimal-notebook can now use issue template , like new-patch-release to have kebechet handle release with changelog.

### CODE REVIEW

**Comment by harshad16** [comment]
@vpavlin  PTAL :)

**Comment by vpavlin** [comment]
@harshad16 I am not sure I understand the init.py and also why the version there does not match the version we are actually about to release

**Comment by harshad16** [comment]
> @harshad16 I am not sure I understand the init.py and also why the version there does not match the version we are actually about to release

i was thinking we could use kebechet, which basically on creating an issue for example new-patch-release, opens  a pr with changelog based on the last release and new release... however for it to do so, it uses python based script to keep track of version, files it support are https://github.com/thoth-station/kebechet/blob/8d9e2acb78405cd1f323daec63279667c7f488da/kebechet/managers/version/version.py#L129
```
"setup.py",
"__init__.py",
"__about__.py",
"version.py",
"app.py",
"wsgi.py",
```
didn't want any user/contributor to get confused so went with __init__.py.

about the release version, was thinking to release a minor version. 
anyway will change it to v0.0.5.

**Comment by vpavlin** [comment]
Ah, ok..sounds good

/lgtm

**Pull request merged**
